package model;
// Generated 14 feb. 2020 17:54:49 by Hibernate Tools 5.2.12.Final

/**
 * Cartas generated by hbm2java
 */
public class Cartas implements java.io.Serializable {

	private Integer idCarta;
	private String marca;
	private String modelo;
	private String pais;
	private Float motor;
	private Integer potenciaKv;
	private Integer numCilindros;
	private Integer velocidad;
	private Integer revoluciones;
	private Float consumo;
	private Integer rondasGanadas;

	public Cartas() {
	}

	public Cartas(String marca, String modelo, String pais, Float motor, Integer potenciaKv, Integer numCilindros,
			Integer velocidad, Integer revoluciones, Float consumo, Integer rondasGanadas) {
		this.marca = marca;
		this.modelo = modelo;
		this.pais = pais;
		this.motor = motor;
		this.potenciaKv = potenciaKv;
		this.numCilindros = numCilindros;
		this.velocidad = velocidad;
		this.revoluciones = revoluciones;
		this.consumo = consumo;
		this.rondasGanadas = rondasGanadas;
	}

	public Integer getIdCarta() {
		return this.idCarta;
	}

	public void setIdCarta(Integer idCarta) {
		this.idCarta = idCarta;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Float getMotor() {
		return this.motor;
	}

	public void setMotor(Float motor) {
		this.motor = motor;
	}

	public Integer getPotenciaKv() {
		return this.potenciaKv;
	}

	public void setPotenciaKv(Integer potenciaKv) {
		this.potenciaKv = potenciaKv;
	}

	public Integer getNumCilindros() {
		return this.numCilindros;
	}

	public void setNumCilindros(Integer numCilindros) {
		this.numCilindros = numCilindros;
	}

	public Integer getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(Integer velocidad) {
		this.velocidad = velocidad;
	}

	public Integer getRevoluciones() {
		return this.revoluciones;
	}

	public void setRevoluciones(Integer revoluciones) {
		this.revoluciones = revoluciones;
	}

	public Float getConsumo() {
		return this.consumo;
	}

	public void setConsumo(Float consumo) {
		this.consumo = consumo;
	}

	public Integer getRondasGanadas() {
		return this.rondasGanadas;
	}

	public void setRondasGanadas(Integer rondasGanadas) {
		this.rondasGanadas = rondasGanadas;
	}

}
