package model;
// Generated 14 feb. 2020 17:54:49 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * Partidas generated by hbm2java
 */
public class Partidas implements java.io.Serializable {

	private Integer idPartida;
	private String idSession;
	private Integer jugadorA;
	private Integer jugadorB;
	private Integer ganador;
	private Boolean terminada;
	private Date fecha;

	public Partidas() {
		terminada = false;
	}

	public Partidas(String idSession, Integer jugadorA, Integer jugadorB, Integer ganador, Boolean terminada,
			Date fecha) {
		this.idSession = idSession;
		this.jugadorA = jugadorA;
		this.jugadorB = jugadorB;
		this.ganador = ganador;
		this.terminada = terminada;
		this.fecha = fecha;
	}

	public Integer getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	public String getIdSession() {
		return this.idSession;
	}

	public void setIdSession(String idSession) {
		this.idSession = idSession;
	}

	public Integer getJugadorA() {
		return this.jugadorA;
	}

	public void setJugadorA(Integer jugadorA) {
		this.jugadorA = jugadorA;
	}

	public Integer getJugadorB() {
		return this.jugadorB;
	}

	public void setJugadorB(Integer jugadorB) {
		this.jugadorB = jugadorB;
	}

	public Integer getGanador() {
		return this.ganador;
	}

	public void setGanador(Integer ganador) {
		this.ganador = ganador;
	}

	public Boolean getTerminada() {
		return this.terminada;
	}

	public void setTerminada(Boolean terminada) {
		this.terminada = terminada;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
